"""Create BuildingLevel with FK to Building

Revision ID: 0ce80f17f643
Revises: caf79b1590fd
Create Date: 2025-07-25 14:11:45.272340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ce80f17f643'
down_revision: Union[str, None] = 'caf79b1590fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('building_level', sa.Column('level_name', sa.String(length=50), nullable=False))
    op.drop_column('building_level', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('building_level', sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('building_level', 'level_name')
    # ### end Alembic commands ###
