"""add_project_foreign_key

Revision ID: 317cc58a5f39
Revises: 64a4cdc07a43
Create Date: 2025-07-26 00:48:44.216243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '317cc58a5f39'
down_revision: Union[str, None] = '64a4cdc07a43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('defect_type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['defect_type_id'], ['defect_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_defect_type_id'), 'recommendations', ['defect_type_id'], unique=False)
    op.create_index(op.f('ix_recommendations_is_deleted'), 'recommendations', ['is_deleted'], unique=False)
    op.drop_index(op.f('ix_token_blacklist_token'), table_name='token_blacklist')
    op.drop_table('token_blacklist')
    op.create_unique_constraint(None, 'building_level', ['id'])
    op.drop_constraint(op.f('building_level_building_id_fkey'), 'building_level', type_='foreignkey')
    op.drop_constraint(op.f('buildings_project_id_fkey'), 'buildings', type_='foreignkey')
    op.drop_column('projects', 'latitude')
    op.drop_column('projects', 'longtitude')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('longtitude', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('projects', sa.Column('latitude', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('buildings_project_id_fkey'), 'buildings', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(op.f('building_level_building_id_fkey'), 'building_level', 'buildings', ['building_id'], ['id'])
    op.drop_constraint(None, 'building_level', type_='unique')
    op.create_table('token_blacklist',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('token_blacklist_pkey'))
    )
    op.create_index(op.f('ix_token_blacklist_token'), 'token_blacklist', ['token'], unique=True)
    op.drop_index(op.f('ix_recommendations_is_deleted'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_defect_type_id'), table_name='recommendations')
    op.drop_table('recommendations')
    # ### end Alembic commands ###
