"""Add building model

Revision ID: 8e13b9cf3059
Revises: 2b00cebfc74d
Create Date: 2025-06-20 12:41:23.770291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e13b9cf3059'
down_revision: Union[str, None] = '2b00cebfc74d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'building_type', ['id'])
    op.add_column('buildings', sa.Column('address', sa.String(length=500), nullable=False))
    op.add_column('buildings', sa.Column('year_built', sa.Integer(), nullable=False))
    op.add_column('buildings', sa.Column('building_type', sa.Integer(), nullable=False))
    op.add_column('buildings', sa.Column('area_sq_meters', sa.Float(), nullable=False))
    op.add_column('buildings', sa.Column('levels_count', sa.Integer(), nullable=False))
    op.add_column('buildings', sa.Column('sides_count', sa.Integer(), nullable=False))
    op.add_column('buildings', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.add_column('buildings', sa.Column('project_id', sa.Integer(), nullable=False))
    op.add_column('buildings', sa.Column('latitude', sa.Float(), nullable=False))
    op.add_column('buildings', sa.Column('longitude', sa.Float(), nullable=False))
    op.add_column('buildings', sa.Column('status_construction', sa.Float(), nullable=False))
    op.add_column('buildings', sa.Column('construction_start_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('buildings', sa.Column('construction_end_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('buildings', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('buildings', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('buildings', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('buildings', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_buildings_is_deleted'), 'buildings', ['is_deleted'], unique=False)
    op.drop_column('buildings', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buildings', sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_buildings_is_deleted'), table_name='buildings')
    op.drop_column('buildings', 'is_deleted')
    op.drop_column('buildings', 'deleted_at')
    op.drop_column('buildings', 'updated_at')
    op.drop_column('buildings', 'created_at')
    op.drop_column('buildings', 'construction_end_date')
    op.drop_column('buildings', 'construction_start_date')
    op.drop_column('buildings', 'status_construction')
    op.drop_column('buildings', 'longitude')
    op.drop_column('buildings', 'latitude')
    op.drop_column('buildings', 'project_id')
    op.drop_column('buildings', 'owner_id')
    op.drop_column('buildings', 'sides_count')
    op.drop_column('buildings', 'levels_count')
    op.drop_column('buildings', 'area_sq_meters')
    op.drop_column('buildings', 'building_type')
    op.drop_column('buildings', 'year_built')
    op.drop_column('buildings', 'address')
    op.drop_constraint(None, 'building_type', type_='unique')
    # ### end Alembic commands ###
